# Generated by Django 4.2.6 on 2023-10-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=50)),
                ('ProductId', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=50)),
                ('Review', models.CharField(max_length=50)),
                ('Rating', models.CharField(max_length=50)),
            ],
        ),
    ]
