# Generated by Django 4.2.6 on 2023-10-25 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_producttb_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=50)),
                ('ProductId', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=50)),
                ('Price', models.CharField(max_length=50)),
            ],
        ),
    ]
