# Generated by Django 4.2.6 on 2023-11-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_wishlisttb'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttb',
            name='Description',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
