# Generated by Django 4.2.6 on 2023-11-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_producttb_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtb',
            name='Status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
