# Generated by Django 4.2.6 on 2023-11-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_registrationtb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=50)),
            ],
        ),
    ]
