# Generated by Django 4.2.6 on 2023-11-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_categorytb'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytb',
            name='CategoryImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
