# Generated by Django 4.2.6 on 2023-11-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_wishlisttb_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlisttb',
            name='ProductImage',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
