# Generated by Django 4.2.6 on 2023-11-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0011_alter_wishlisttb_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=50)),
                ('UserName', models.CharField(max_length=50)),
                ('ProductId', models.CharField(max_length=50)),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductImage', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('CartId', models.CharField(max_length=50)),
                ('TotalAmount', models.CharField(max_length=50)),
                ('OrderStatus', models.CharField(max_length=50)),
            ],
        ),
    ]
