# Generated by Django 4.2.6 on 2023-11-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0012_ordertb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlisttb',
            name='ProductImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
