# Generated by Django 4.2.6 on 2023-11-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0013_alter_wishlisttb_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttb',
            name='ProductImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
