# Generated by Django 4.2.6 on 2023-11-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0014_carttb_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertb',
            name='ProductImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
