# Generated by Django 4.2.6 on 2023-11-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0015_alter_ordertb_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carttb',
            name='CartStatus',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
