# Generated by Django 4.2.6 on 2023-11-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0016_carttb_cartstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlisttb',
            name='Category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
