# Generated by Django 4.2.6 on 2023-11-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0017_wishlisttb_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlisttb',
            name='Category',
        ),
        migrations.AddField(
            model_name='carttb',
            name='Category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
