# Generated by Django 4.2.6 on 2023-11-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0018_remove_wishlisttb_category_carttb_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertb',
            name='CartId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
