# Generated by Django 4.2.6 on 2023-11-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0020_paymenttb'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttb',
            name='Address',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
