# Generated by Django 4.2.6 on 2023-11-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0021_paymenttb_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttb',
            name='OrderId',
        ),
    ]
