# Generated by Django 4.2.6 on 2023-11-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0022_remove_paymenttb_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttb',
            name='ItemCheck',
            field=models.BooleanField(blank=True, null=True, verbose_name=False),
        ),
    ]
