# Generated by Django 4.2.6 on 2023-11-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0026_alter_ordertb_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertb',
            name='CartId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
